name: exorcise
channels:
  - r
  - defaults
  - anaconda
  - bioconda
  - conda-forge
dependencies:
  - _r-mutex
  - argcomplete
  - bioconductor-annotationdbi
  - bioconductor-biobase
  - bioconductor-biocfilecache
  - bioconductor-biocgenerics
  - bioconductor-biomart=2.54.0
  - bioconductor-biostrings
  - bioconductor-data-packages
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicranges=1.50.0
  - bioconductor-iranges=2.32.0
  - bioconductor-keggrest
  - bioconductor-s4vectors
  - bioconductor-xvector
  - bioconductor-zlibbioc
  - blas
  - blat=35
  - bottleneck
  - brotli
  - brotli-bin
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - cctools_osx-64
  - clang
  - clang-14
  - clang_osx-64
  - clangxx
  - clangxx_osx-64
  - compiler-rt
  - compiler-rt_osx-64
  - curl
  - cycler
  - cyrus-sasl
  - expat
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-anaconda
  - fonts-conda-ecosystem
  - fonttools
  - freetype
  - fribidi
  - gettext
  - gfortran_impl_osx-64
  - gfortran_osx-64
  - giflib
  - glib
  - glib-tools
  - gmp
  - graphite2
  - gsl
  - harfbuzz
  - icu
  - importlib-metadata
  - importlib_metadata
  - intel-openmp
  - isl
  - jpeg
  - jq
  - kiwisolver
  - krb5
  - lcms2
  - ld64_osx-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libclang-cpp14
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran-devel_osx-64
  - libgfortran5
  - libglib
  - libiconv
  - liblapack
  - libllvm14
  - libnghttp2
  - libntlm
  - libopenblas
  - libpng
  - libsqlite
  - libssh2
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libzlib
  - llvm-openmp
  - llvm-tools
  - lz4-c
  - make
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - munkres
  - ncurses
  - numexpr
  - oniguruma
  - openjdk
  - openssl
  - pandas
  - pandoc
  - pango
  - pcre2
  - pillow
  - pip
  - pixman
  - pyparsing
  - python=3.7.12
  - python-dateutil
  - python_abi
  - pyyaml
  - r=4.2
  - r-askpass
  - r-assertthat
  - r-base
  - r-base64enc
  - r-biocmanager
  - r-bit
  - r-bit64
  - r-bitops
  - r-blob
  - r-boot
  - r-bslib
  - r-cachem
  - r-catools
  - r-cellranger
  - r-class
  - r-cli
  - r-clipr
  - r-cluster
  - r-codetools
  - r-colorspace
  - r-commonmark
  - r-config
  - r-cpp11
  - r-crayon
  - r-crosstalk
  - r-curl
  - r-data.table
  - r-dbi
  - r-dbplyr
  - r-digest
  - r-dplyr=1.0.10
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-farver
  - r-fastmap
  - r-filelock
  - r-fontawesome
  - r-forcats
  - r-foreach
  - r-foreign
  - r-forge
  - r-fs
  - r-generics
  - r-getopt
  - r-ggplot2
  - r-ggrepel
  - r-globals
  - r-glue
  - r-gtable
  - r-haven
  - r-hexbin
  - r-highr
  - r-hms
  - r-htmltools
  - r-htmlwidgets
  - r-httpuv
  - r-httr
  - r-isoband
  - r-iterators
  - r-jquerylib
  - r-jsonlite
  - r-kernsmooth
  - r-knitr
  - r-labeling
  - r-later
  - r-lattice
  - r-lazyeval
  - r-lifecycle
  - r-logger=0.2.2
  - r-magrittr
  - r-markdown
  - r-mass
  - r-matrix
  - r-memoise
  - r-mgcv
  - r-mime
  - r-miniui
  - r-mongolite
  - r-munsell
  - r-nlme
  - r-nnet
  - r-odbc
  - r-openssl
  - r-optparse=1.7.3
  - r-packrat
  - r-pillar
  - r-pkgconfig
  - r-pki
  - r-plogr
  - r-plotly
  - r-png
  - r-prettyunits
  - r-profvis
  - r-progress
  - r-promises
  - r-purrr
  - r-r.methodss3
  - r-r.oo
  - r-r.utils
  - r-r2d3
  - r-r6
  - r-rappdirs
  - r-rcolorbrewer
  - r-rcpp
  - r-rcurl
  - r-readr
  - r-readxl=1.4.1
  - r-recommended
  - r-rematch
  - r-rjava
  - r-rjdbc
  - r-rjson
  - r-rjsonio
  - r-rlang
  - r-rmarkdown
  - r-rpart
  - r-rprojroot
  - r-rsconnect
  - r-rsqlite
  - r-rstudioapi
  - r-sass
  - r-scales
  - r-shiny
  - r-sourcetools
  - r-sparklyr
  - r-spatial
  - r-stringi
  - r-stringr
  - r-survival
  - r-sys
  - r-tibble=3.1.8
  - r-tidyr=1.2.1
  - r-tidyselect=1.2.0
  - r-tinytex
  - r-tzdb
  - r-utf8
  - r-uuid
  - r-vctrs
  - r-viridislite
  - r-vroom
  - r-withr
  - r-writexl
  - r-xfun
  - r-xml
  - r-xml2
  - r-xtable
  - r-yaml
  - readline
  - rstudio
  - seaborn=0.12.2
  - setuptools
  - sigtool
  - six
  - sqlite
  - tapi
  - tk
  - tktable
  - toml
  - tornado
  - typing_extensions
  - tzdata
  - unixodbc
  - wheel
  - xmltodict
  - xz
  - yaml
  - yq
  - zipp
  - zlib
  - zstd
  - pip:
      - attrdict==2.0.1
      - et-xmlfile
      - joblib
      - numpy==1.21.6
      - openpyxl
      - packaging
      - patsy
      - pytz
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - statsmodels==0.13.5
      - threadpoolctl
      - xlsxwriter==3.0.8
