name: crispieR
channels:
  - r
  - rdonnellyr
  - bioconda
  - anaconda
  - conda-forge
  - defaults
  - free
dependencies:
  - r
  - r-optparse
  - r-dplyr
  - r-data.table
  - r-readxl
  - r-writexl
  - r-tidyr
  - r-tidyselect
  - r-foreach
  - r-logger
  - r-r.utils
  - r-biocmanager
  - r-plotly
  - bioconductor-biomart
  - bioconductor-genomicranges
  - blat
